-   hosts: elasticsearch
    gather_facts: no
    vars:
        es_config_single_node:
            path.data: /var/lib/elasticsearch
            path.logs: /var/log/elasticsearch
            cluster.name: logs
            node.name: elasticsearch
            network.host: 0.0.0.0
            discovery.type: single-node
        es_config_multiple_nodes:
            path.data: /var/lib/elasticsearch
            path.logs: /var/log/elasticsearch
            cluster.name: logs
            node.name: elasticsearch
            network.host: 0.0.0.0
            discovery.seed_hosts: "{{groups.elasticsearch}}"
            cluster.initial_master_nodes: "{{groups.elasticsearch}}"
        es_config: "{{es_config_single_node if (groups.elasticsearch|length) == 1 else es_config_multiple_nodes}}"
    tasks:
    -   group:
            name: elasticsearch
            system: yes
    -   user:
            name: elasticsearch
            system: yes
    -   filesystem:
            dev: /dev/vdb
            fstype: ext4
    -   mount:
            path: /var/lib/elasticsearch
            src: /dev/vdb
            fstype: ext4
            state: mounted
    -   file:
            path: /var/lib/elasticsearch
            state: directory
            owner: elasticsearch
            group: elasticsearch
    -   get_url:
            url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.10.2-amd64.deb
            dest: /opt/elasticsearch-oss-7.10.2-amd64.deb
    -   apt:
            deb: /opt/elasticsearch-oss-7.10.2-amd64.deb
    -   copy:
            dest: /etc/elasticsearch/elasticsearch.yml
            content: "{{es_config}}"
        notify: restart elasticsearch
    handlers:
    -   name: restart elasticsearch
        service:
            name: elasticsearch
            state: restarted
    post_tasks:
    -   name: start, enable elasticsearch
        service:
            name: elasticsearch
            state: started
            enabled: yes
